language: c
compiler:
  - gcc
script: CC="${MYCC}" make ${SHARED} test_standalone >test_gcc_1.txt 2>test_gcc_2.txt && ./test >test_std.txt 2>test_err.txt
env:
  - MYCC="gcc" SHARED=""
  - MYCC="gcc -m32" SHARED=""
  - MYCC="gcc-4.8" SHARED=""
  - MYCC="gcc-4.8 -m32" SHARED=""
  - MYCC="gcc-4.9" SHARED=""
  - MYCC="gcc-4.9 -m32" SHARED=""
  - MYCC="gcc" SHARED="-f makefile.shared"
  - MYCC="gcc -m32" SHARED="-f makefile.shared"
  - MYCC="gcc-4.8" SHARED="-f makefile.shared"
  - MYCC="gcc-4.8 -m32" SHARED="-f makefile.shared"
  - MYCC="gcc-4.9" SHARED="-f makefile.shared"
  - MYCC="gcc-4.9 -m32" SHARED="-f makefile.shared"
matrix:
  fast_finish: true
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.9-multilib gcc-4.8-multilib gcc-multilib build-essential
after_failure:
  - cat test_gcc_1.txt
  - cat test_std.txt
  - cat test_err.txt
after_script:
  - cat test_gcc_2.txt
notifications:
  irc: "chat.freenode.net#libtom-notifications"

