#!/bin/bash

#Change this so it isn't dependent on the folder name
for capsule in `ls testdata`; do
    name=$(basename "$capsule")
    echo "Making $name"
    cmd/cgen/cgen encode -n $name -p testdata/$name/ -o testdata/$name/
done
